DATASET:
  NAME: "vg"
  MODE: "benchmark"
  TRAIN_BATCH_SIZE: 6
  TEST_BATCH_SIZE: 1
MODEL:
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  ALGORITHM: "sg_baseline"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 384
  ROI_BOX_HEAD:
    NUM_CLASSES: 151
  RELATION_ON: True
  ROI_RELATION_HEAD:
    NUM_CLASSES: 51
SOLVER:
  BASE_LR: 5e-3
  MAX_ITER: 100000
  STEPS: (70000,90000)
  CHECKPOINT_PERIOD: 5000
